name: Release

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    - name: Setup System
      run: sudo apt-get install libsqlite3-dev
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec spec
  version:
    name: Create version
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_SEPHORA_BOT }} # Needs a token that has push access to protected branches
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}
      - name: Setup git config
        run: |
          git config user.name "Sephora Bot"
          git config user.email "devops+gh-sephora-bot@sephoradigital.com"
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEPHORA_BOT }} # Needs a token that has push access to protected branches
        run: |
          yarn install --frozen-lockfile
          yarn run auto shipit
  publish:
    name: Publish gem
    runs-on: ubuntu-latest
    needs: [test, version]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Build and publish gem to github package registry
        uses: jstastny/publish-gem-to-github@master
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: sephora-asia
      - name: Build and publish gem to rubygems.org
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}